// packages/solid/src/zikofy/domify.js
import { render } from "solid-js/web";

export function domify(Component, props = {}) {
  const container = document.createElement("div");

  render(() => {
    if (typeof Component === "function") {
      return Component(props);
    }
    return Component;
  }, container);

  if(container.children.length === 1) return container.firstChild;
  return [...container.children];

}

// packages/react/src/zikofy/domify.js
import { createRoot } from "react-dom/client";
import { flushSync } from "react-dom"
import { isValidElement, createElement } from "react";

export const domify = (Component, props = {}) => {
  const container = document.createElement("div");
  const root = createRoot(container);

  const isJsx = isValidElement(Component);

  flushSync(() => {
    root.render(
      isJsx ? Component : createElement(Component, props)
    );
  });

  const el = container.firstElementChild;
  root.unmount();
  return el
};
